import { useEffect, useState } from 'react';
import { FileInput, FileSearch, GitMerge, ShieldCheck, Send, ListChecks, ArrowRight, Check, ShieldAlert, Play, CircleAlert, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { stages } from '@/data/replay';
import { savedRuns, stepSeconds } from '@/astra/saved-runs';
import { useReplay, sourceLabel, type RunStep } from './replay-context';
import { ClassPill, EmptyStage, title } from './primitives';

const steps: (RunStep | null)[] = [null, 'Extract', 'Reconcile', 'Policy check', 'Communicate', 'Verify'];
const secs = (s: number) => s < 1 ? `${s.toFixed(1)} s` : `${Math.round(s)} s`;

export function Analysis(){
 const {stage,reference,source,select,runState,runStage}=useReplay();
 const n=stage.stage; const state=runState[n]; const saved=savedRuns[n-1];
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{if(state?.status!=='running')return;const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[state?.status]);
 const running=state?.status==='running'; const lastLive=state?.status==='done'?state.run:null;
 const prevIds=new Set(n>1?stages[n-2]!.evidence.map(e=>e.id):[]);
 const fresh=reference.evidence.filter(e=>!prevIds.has(e.id)).length;
 const live=stage.claims.filter(c=>!c.superseded_by);
 const capped=live.filter(c=>c.proposed_class!==c.class).length;
 const count=(k:string)=>stage.changes.filter(c=>c.change===k).length;
 const changeLine=stage.changes.length?[['UPGRADED','upgraded'],['DOWNGRADED','downgraded'],['MERGED','merged'],['NEW','new'],['CONFLICT','conflict']].filter(([k])=>count(k!)).map(([k,l])=>`${count(k!)} ${l}`).join(' · '):'—';
 const drafts=[stage.drafts.executive,stage.drafts.engineering,stage.drafts.customer.confirmed_only,...(stage.drafts.customer.early_incident&&stage.drafts.customer.early_incident!==stage.drafts.customer.confirmed_only?[stage.drafts.customer.early_incident]:[])].filter(Boolean);
 const sentences=drafts.flatMap(d=>d!.sections.flatMap(s=>s.sentences));
 const verified=sentences.filter(s=>s.verify?.pass!==false).length;
 const timings=source==='astra_live'&&lastLive?lastLive.timings:saved?.timings??[];
 const extractCount=source==='astra_live'&&lastLive?lastLive.extractCount:source==='astra_saved'?saved?.extractCount:null;
 const t=(k:string)=>{const s=stepSeconds(timings as never,k);return s?` · ${secs(s)}`:'';};
 const cards=[{name:'Evidence in',tag:'Replay',icon:FileInput,value:`${fresh} new · ${reference.evidence.length} total`,line:`Only evidence up to ${stage.at}`},{name:'Extract',tag:'GPT-6 Astra',icon:FileSearch,value:extractCount!=null?`${extractCount} candidates${t('EXTRACT')}`:'—',line:'Checkable statements with source ids'},{name:'Reconcile',tag:'GPT-6 Astra',icon:GitMerge,value:changeLine,line:'Merged into the ledger, every change recorded'},{name:'Policy check',tag:'Code',icon:ShieldCheck,value:`${capped} capped`,line:'Classes capped by provenance, not by wording'},{name:'Communicate',tag:'GPT-6 Astra',icon:Send,value:drafts.length?`${drafts.length} updates`:'—',line:'Every sentence cites a claim or one of our actions'},{name:'Verify',tag:'Code + GPT-6 Astra',icon:ListChecks,value:sentences.length?`${verified}/${sentences.length} sentences`:'—',line:'Rules in code, then support checked by GPT-6 Astra'}];
 const activeCard=running?steps.indexOf(state.step):-1;
 const elapsed=running?Math.max(0,Math.round((now-state.startedAt)/1000)):0;
 const refById=new Map(reference.claims.filter(c=>!c.superseded_by).map(c=>[c.id,c]));
 const matches=live.filter(c=>refById.get(c.id)?.class===c.class).length;
 const savedLine=saved&&n<9?`Saved run · ${new Date(saved.generated_at).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'UTC'})} UTC · ${secs(saved.seconds)} · verify ${saved.verifyPass?'passed':saved.verifyStatus}`:null;
 const status=running?`${state.step}… ${elapsed} s`:lastLive?(lastLive.pass?`Done in ${secs(lastLive.seconds)}. Passed verify — the replay now shows this run.`:`Done in ${secs(lastLive.seconds)}, but verify excluded ${lastLive.summary.reduce((s,a)=>s+a.total-a.verified,0)} sentence(s). The replay keeps ${source==='reference'?'the reference data':'the previous run'}.`):source==='reference'?(savedLine?`${savedLine}. It didn't pass verify, so the replay shows reference data.`:'No GPT-6 Astra run for this stage yet. Showing reference data.'):`Showing ${sourceLabel(source)}.`;
 return <div className="analysis-page"><header className="analysis-heading"><div><span className="eyebrow">STAGE {n} / 9</span><h1>Analysis · {stage.label} · {stage.at}{n<9?' UTC':''}</h1><p>What GPT-6 Astra did for this stage, and how it was checked.</p></div><span className="neutral-badge">{sourceLabel(source)}</span></header>
 {state?.status==='failed'&&<div className="analysis-banner error"><CircleAlert/>{state.httpStatus===402?'Lovable AI credits are used up. Add credits in Settings → Plans & credits.':state.httpStatus===429?'GPT-6 Astra is busy right now. Wait a minute, then try again.':`${state.error}.`} The stage keeps its {source==='reference'?'reference data':'previous run'}.<Button variant="outline" size="sm" onClick={()=>void runStage(n)}>Try again</Button></div>}
 <section className="pipeline"><h2>Analysis pipeline</h2><div className="pipeline-grid">{cards.map((c,i)=><div className={`pipeline-item ${activeCard===i||(running&&state.step==='Communicate'&&i===4)?'running':''}`} key={c.name}><article className="pipeline-card"><div className="pipeline-card-top"><span className="step-number">{i+1}</span><h3>{c.name}</h3></div><span className="neutral-badge">{c.tag}</span><c.icon size={23} className="pipeline-icon"/><strong className="pipeline-value">{c.value}</strong>{i===1&&extractCount==null&&<span className="muted">Run this stage to see</span>}<p>{c.line}</p></article>{i<5&&<ArrowRight className="pipeline-arrow" size={15}/>}</div>)}</div></section>
 <section className="run-section"><div><p>{status}</p><span className="muted">{n===9?'The post-incident pack keeps its reference drafts.':'About 3 minutes. The replay keeps using the saved run until this one passes verify.'}</span>{lastLive&&!running&&<span className="muted"> {lastLive.summary.map(a=>`${title(a.audience)}${a.policy_mode?` (${a.policy_mode.replace('_',' ')})`:''} ${a.verified}/${a.total}`).join(' · ')}</span>}</div><Button disabled={running||n===9} onClick={()=>void runStage(n)}><Play size={14}/>{running?'Running…':'Run this stage with GPT-6 Astra'}</Button></section>
 {!live.length?<EmptyStage jump={()=>select(4)}/>:<section className="golden-section"><header className="row-between"><h2>Golden replay check</h2><span className={matches===live.length?'text-success':'muted'}>{matches===live.length?<Check size={15}/>:null} {matches}/{live.length} match</span></header><p className="golden-summary">{matches}/{live.length} claims match the golden ledger ({capped} after the policy cap) · {sentences.length-verified} unsupported sentences</p><table><thead><tr><th>Claim</th><th>Expected</th><th>GPT-6 Astra proposed</th><th>After policy</th><th>Result</th></tr></thead><tbody>{live.map(c=>{const ref=refById.get(c.id);const ok=ref?.class===c.class;return <tr key={c.id}><td><span className="mono">{c.id}</span><span className="table-statement">{c.statement}</span></td><td>{ref?<ClassPill cls={ref.class}/>:<span className="muted">Not in golden</span>}</td><td><ClassPill cls={c.proposed_class}/></td><td><ClassPill cls={c.class}/></td><td className={ok?'text-success':'muted'}>{ok?(c.class!==c.proposed_class?<><ShieldAlert size={14}/>Capped, then match</>:<><Check size={14}/>Match</>):<><X size={14}/>Differs</>}</td></tr>;})}</tbody></table><h3>Must not say</h3><div className="must-not-say">{stage.must_not_say.map(s=>{const said=sentences.some(x=>x.text.toLowerCase().includes(s.toLowerCase()));return <div key={s}><span>{s}</span><span className={said?'muted':'text-success'}>{said?'✕ Said':'✓ Not said'}</span></div>;})}</div></section>}
 <section className="provenance-box"><ShieldCheck size={22}/><div><h2>Decided by provenance, not by how convincing the text sounds</h2><p><strong>CONFIRMED</strong> only with an organisation's own channel about itself or our internal systems (claims about us). <strong>REPORTED</strong> needs 2+ independent non-official sources, 1 monitor / press source, or 1 official source about someone else; anything else is at most <strong>UNCONFIRMED</strong>. <strong>CONFLICTING</strong> when credible sources disagree (both kept). <strong>UNKNOWN</strong> for questions nothing answers. A provider's status page outranks its other channels.</p></div></section></div>;
}
