import { useEffect } from 'react';
import { X, ExternalLink, Clock } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useReplay } from './replay-context';
import { ClassPill, ClaimChip, Capped, kinds, title } from './primitives';
export type Selection={type:'claim'|'evidence'|'response';id:string};
export function DetailDrawer({selection,close,open}:{selection:Selection;close:()=>void;open:(s:Selection)=>void}){const {stage,additions}=useReplay();useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key==='Escape')close();};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h);},[close]);
 const claim=stage.claims.find(c=>selection.type==='claim'&&c.id===selection.id);const evidence=stage.evidence.find(e=>selection.type==='evidence'&&e.id===selection.id);const response=[...stage.response_items,...(additions[stage.stage]??[])].find(r=>selection.type==='response'&&r.id===selection.id);
 const drafts=[stage.drafts.executive,stage.drafts.engineering,stage.drafts.customer.confirmed_only];const used=drafts.flatMap(d=>d?d.sections.flatMap(s=>s.sentences.filter(sentence=>selection.type==='claim'?sentence.claim_ids.includes(selection.id):sentence.response_ids.includes(selection.id)).map(sentence=>({audience:d.audience,text:sentence.text}))):[]);
 const source=(e:NonNullable<typeof evidence>)=><article className="drawer-source" key={e.id}><div className="row-between"><span className="neutral-badge">{kinds[e.kind]}</span><span className="mono">{e.id} · {e.at} UTC</span></div><strong>{e.origin}</strong>{e.fictional&&<span className="neutral-badge">Fictional</span>}<blockquote>“{e.excerpt}”</blockquote>{!e.fictional&&e.url&&<a href={e.url} target="_blank" rel="noreferrer">Open source <ExternalLink size={13}/></a>}</article>;
 return <aside className="detail-drawer" aria-label="Detail drawer"><header className="row-between"><span className="eyebrow">{title(selection.type)} details</span><Button variant="ghost" size="icon" aria-label="Close details" onClick={close}><X/></Button></header><div className="drawer-body">{claim&&<><div className="drawer-title"><ClassPill cls={claim.class}/><span className="mono">{claim.id}</span></div><Capped claim={claim}/><h2>{claim.statement}</h2>{claim.proposed_class!==claim.class&&<div className="policy-explanation">GPT-6 Astra proposed {title(claim.proposed_class)}. Policy allows {title(claim.class)}: CONFIRMED needs the provider's own channel or our systems; REPORTED needs two independent sources or one other company, monitor or press source.</div>}<h3>Sources</h3>{claim.source_ids.length?claim.source_ids.map(id=>{const e=stage.evidence.find(e=>e.id===id);return e?source(e):null;}):<p className="muted">No sources yet</p>}{claim.provider_wording&&<><h3>Provider's own words</h3><blockquote>“{claim.provider_wording}”</blockquote></>}{claim.settled_by&&<><h3>Would be settled by</h3><p>{claim.settled_by}</p></>}{claim.estimate&&<p><Clock size={15}/>{claim.estimate.speaker} expects “{claim.estimate.said}” · said {claim.estimate.at} · estimate, not a fact.</p>}<h3>History</h3>{claim.history.map((h,i)=><div className="history-entry" key={i}><span className="mono">{h.stage===4?'18:51':h.stage===3?'18:11':h.stage===2?'18:02':'17:56'}</span><ClassPill cls={h.class}/><p>{h.statement}</p><div>{h.because.map(id=><Button key={id} variant="link" size="sm" onClick={()=>open({type:'evidence',id})}>{id}</Button>)}</div></div>)}</>}{evidence&&<><h2>{evidence.origin}</h2><p className="muted">Arrived via {evidence.arrived_via}</p>{source(evidence)}<h3>Raised</h3>{stage.claims.filter(c=>!c.superseded_by&&c.source_ids.includes(evidence.id)).map(c=><ClaimChip key={c.id} claim={c} onClick={()=>open({type:'claim',id:c.id})}/>)}{!stage.claims.some(c=>!c.superseded_by&&c.source_ids.includes(evidence.id))&&<p>—</p>}</>}{response&&<><span className="neutral-badge">{response.type.replaceAll('_',' ')}</span><h2>{response.text}</h2><p>{response.by} · <span className="mono">{response.at} UTC</span></p>{response.status&&<p>Status: {response.status}</p>}{response.decision&&<p>Decided {response.decided_at}: {response.decision}</p>}{response.replaced_by&&<Button variant="link" onClick={()=>open({type:'response',id:response.replaced_by??''})}>Replaced by {response.replaced_by}</Button>}</>}{selection.type!=='evidence'&&<><h3>Used in</h3>{used.length?used.map((u,i)=><div className="used-in" key={i}><strong>{title(u.audience)} · </strong>{u.text}</div>):<p className="muted">Not in the current updates.</p>}</>}</div></aside>;
}
