import { KeyFacts } from './key-facts';
import { Button } from '@/components/ui/button';
import { ClassPill, ClaimChip, title } from './primitives';
import type { Claim, Draft, Stage } from '@/data/replay/types';

type Props = { stage: Stage; openClaim: (id: string) => void; openSource: (id: string) => void; openResponse: (id: string) => void };
export function PostIncidentReports({ stage, openClaim, openSource }: Props) {
 const reports = stage.evidence.filter(e => e.channel === 'report' || e.at.startsWith('12 Jun') || e.at.startsWith('13 Jun'));
 return <div className="column-scroll post-content"><span className="eyebrow">13 JUN 2025 · PROVIDER REPORTS</span><h2>The record, after the incident</h2>{reports.map(e => <article className="evidence-card" key={e.id}><div className="evidence-top"><span className="mono">{e.at} UTC · {e.id}</span></div><h3>{e.origin}</h3><blockquote className="post-report-excerpt">“{e.excerpt}”</blockquote><div className="raised">{stage.claims.filter(c => !c.superseded_by && c.source_ids.includes(e.id)).map(c => <ClaimChip key={c.id} claim={c} onClick={() => openClaim(c.id)}/>)}</div><Button variant="link" size="sm" className="more-button" onClick={() => openSource(e.id)}>Source details</Button></article>)}</div>;
}
export function PostIncidentChecks({stage, openClaim, openSource, openResponse}: Props) {
 const claim = (id: string) => stage.claims.find(c => c.id === id);
 const claimRecord = (c: Claim) => <div key={c.id} className="post-claim"><div className="post-claim-heading"><ClassPill cls={c.class}/><ClaimChip claim={c} onClick={() => openClaim(c.id)}/></div><p>{c.statement}</p><div className="post-sources">{c.source_ids.map(id => <Button key={id} variant="link" size="sm" onClick={() => openSource(id)}>{id}</Button>)}</div></div>;
 const checks = stage.drafts.executive?.sections.flatMap(s => s.sentences) ?? [];
 const passed = checks.filter(s => s.verify?.pass === true).length;
 return <div className="column-scroll post-content"><section><h2>Provider-report summary</h2>{['C-003','C-031','C-033'].flatMap(id => {const c=claim(id);return c?[claimRecord(c)]:[];})}<h3>Three clocks, not one</h3>{['C-029','C-030','C-028'].flatMap(id => {const c=claim(id);return c?[claimRecord(c)]:[];})}</section><section><h2>How the story changed</h2>{stage.changes.map(change => {const c=claim(change.claim_id);if(!c)return null;const previous=c.history.filter(h=>h.stage<9).at(-1);const target=c.superseded_by?claim(c.superseded_by):undefined;return <article className="post-story" key={c.id}><div className="post-claim-heading"><ClassPill cls={c.class}/><ClaimChip claim={c} onClick={()=>openClaim(c.id)}/><span className="muted">{change.change==='MERGED'?`Merged into ${c.superseded_by}`:change.from?`${title(change.from)} → ${title(change.to??c.class)}`:`New · ${title(c.class)}`}</span></div>{previous&&<p className="muted">Then: {previous.statement}</p>}<p>Now: {(target??c).statement}</p>{target&&<div className="post-claim-heading"><ClassPill cls={target.class}/><ClaimChip claim={target} onClick={()=>openClaim(target.id)}/></div>}<div className="post-sources">{change.because.map(id=><Button key={id} variant="link" size="sm" onClick={()=>openSource(id)}>{id}</Button>)}</div></article>;})}</section><section><h2>Statement checks</h2><p className={passed===checks.length?'text-success':'text-warning'}>{passed}/{checks.length} still hold.{passed===checks.length?' Nothing in this retrospective needs correcting.':''}</p>{checks.map((sentence,i)=><article className="post-story" key={i}><span className={sentence.verify?.pass?'text-success':'text-warning'}>{sentence.verify?.pass?'✓ Still holds':'⚠ Needs correction'}</span><p>{sentence.text}</p><div className="post-claim-heading">{sentence.claim_ids.map(id=>{const c=claim(id);return c?<span className="post-claim-heading" key={id}><ClassPill cls={c.class}/><ClaimChip claim={c} onClick={()=>openClaim(id)}/></span>:null;})}{sentence.response_ids.map(id=><Button key={id} variant="outline" size="sm" className="citation response-citation" onClick={()=>openResponse(id)}>{id}</Button>)}</div>{sentence.verify?.reason&&<p className="text-warning">{sentence.verify.reason}</p>}</article>)}</section><section><h2>Our actions</h2>{stage.response_items.filter(r=>r.at.startsWith('13 Jun')).map(r=><article className="post-story" key={r.id}><Button variant="link" size="sm" className="more-button" onClick={()=>openResponse(r.id)}>{r.id} · {title(r.type.replaceAll('_',' '))}</Button><p>{r.text}</p><p className="muted">{r.by} · {r.at} UTC{r.status==='open'?' · Open':''}</p></article>)}</section></div>;
}
export function PostIncidentDraft({ draft, stage, openClaim, openResponse, footer }: { draft: Draft; stage: Stage; openClaim: (id: string) => void; openResponse: (id: string) => void; footer: React.ReactNode }) {
 return <article className="draft-card post-draft"><header><h2>{draft.audience==='customer'?'Customer incident report':`${title(draft.audience)} retrospective`} <span className="muted">· {draft.as_of}</span></h2><span className="neutral-badge">Reference draft</span></header><div className="draft-body">{draft.sections.map((section,i)=><section className="draft-section" key={i}><h3>{section.heading}</h3>{section.sentences.map((sentence,j)=><div className={`draft-sentence ${sentence.verify?.pass===false?'failed-sentence':''}`} key={j}><span className="sentence-text">{sentence.text}</span><span className="sentence-citations">{sentence.claim_ids.map(id=><ClaimChip key={id} id={id} claim={stage.claims.find(c=>c.id===id)} onClick={()=>openClaim(id)}/>)}{sentence.response_ids.map(id=><Button key={id} variant="outline" size="sm" className="citation response-citation" onClick={()=>openResponse(id)}>{id}</Button>)}</span>{sentence.verify?.pass===false&&<p className="verify-reason">✕ Not supported: {sentence.verify.reason}</p>}</div>)}</section>)}<KeyFacts draft={draft} claims={stage.claims} openClaim={openClaim}/></div>{footer}</article>;
}