import { Link } from '@tanstack/react-router';
import { Zap, Play, Pause, ChevronLeft, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useReplay } from './replay-context';
import { stages } from '@/data/replay';
import { capturedTime } from './incident-data';
export function DeskShell({children}:{children:React.ReactNode}){const {stage,select,playing,setPlaying,run,isLive,setLive}=useReplay();const reachable=stage.sources_reachable;const sourceTitle=`Google Cloud status ${reachable.google_status?'✓':'✕'} · Cloudflare status ${reachable.cloudflare_status?'✓':'✕'} · GPT-6 Astra ${reachable.astra&&run!=='unreachable'?'✓':'✕'}`;const elapsed=Number(stage.label.slice(2));const times=[5,10,20,60,110,130,190,220];
  return <div className="app-shell"><header className="topbar"><div className="brand"><Zap size={20} fill="currentColor"/><span>Outage Desk</span></div><nav aria-label="Main navigation"><Link to="/" search={{stage:stage.stage,run:run||undefined}} activeOptions={{exact:true}} activeProps={{className:'active'}}>Desk</Link><Link to="/analysis" search={{stage:stage.stage,run:run||undefined}} activeProps={{className:'active'}}>Analysis</Link></nav><div className="incident-info"><h1 className="incident-title">{isLive?'ASOS app notification · live':'Google Cloud API outage — Northwind impact'}</h1><div className="incident-meta">{isLive?<span className="status-badge"><i className="dot-success"/>Live</span>:<><span className="status-badge"><i className={stage.stage<5?'dot-danger':stage.stage<8?'dot-warning':'dot-success'}/>{stage.status}</span><span className="priority">P1</span><span className="mono">Started 17:51 UTC</span><span className="mono elapsed">{stage.stage===9?'13 Jun':`${stage.label} · ${Math.floor(elapsed/60)} h ${String(elapsed%60).padStart(2,'0')} m`}</span><span className="neutral-badge replay-badge">Replay · 12 Jun 2025</span><span className="source-health" title={sourceTitle} aria-label={sourceTitle}>{[reachable.google_status,reachable.cloudflare_status,reachable.astra&&run!=='unreachable'].map((v,i)=><i key={i} className={v?'dot-success':'dot-warning'}/>)}</span></>}</div></div></header>
 <section className={`replay-bar replay-${stage.stage<5?'investigating':stage.stage<8?'recovering':'resolved'}`} aria-label="Incident replay">{isLive?<div className="live-caption">Live · ASOS app notification · captured {capturedTime} BST</div>:<><div className="playback"><Button variant="outline" size="icon" aria-label={playing?'Pause replay':'Play replay'} title={playing?'Pause replay':'Play replay'} onClick={()=>setPlaying(!playing)}>{playing?<Pause/>:<Play fill="currentColor"/>}</Button><div><Button variant="ghost" size="icon" aria-label="Previous stage" disabled={stage.stage===1} onClick={()=>select(stage.stage-1)}><ChevronLeft/></Button><Button variant="ghost" size="icon" aria-label="Next stage" disabled={stage.stage===9} onClick={()=>select(stage.stage+1)}><ChevronRight/></Button></div></div><div className="replay-details"><div className="replay-caption"><span className="mono replay-time">{stage.at}{stage.stage<9?' UTC':''}</span><strong>{stage.title}</strong></div><div className="timeline"><div className="axis"><div className="axis-fill" style={{width:`${stage.stage===9?100:(stage.stage-1)/7*100}%`}}/>{times.map((t,i)=><div className="stage-marker" style={{left:`${i/7*100}%`}} key={t}><Button variant="ghost" aria-label={`Stage ${i+1}: ${stages[i]?.title}`} aria-current={stage.stage===i+1?'step':undefined} className={`diamond ${stage.stage===i+1?'current':stage.stage>i+1?'past':''}`} onClick={()=>select(i+1)}/><span className="mono">T+{t}</span></div>)}{stage.evidence.map(e=>{const [h=0,m=0]=e.at.split(':').map(Number);return <i key={e.id} title={`${e.id} · ${e.at}`} className="evidence-tick" style={{left:`${(h*60+m-1071)/220*100}%`}}/>;})}</div><div className="next-day" title="Next day"><span className="dashed-gap"/><Button variant="ghost" className={`diamond ${stage.stage===9?'current':''}`} aria-label="Stage 9: Next day report" onClick={()=>select(9)}/><span className="mono">Report</span></div></div></div></>}<Button variant="outline" size="sm" className={`live-chip ${isLive?'selected':''}`} aria-pressed={isLive} title={isLive?'Return to replay':'Show ASOS incident'} onClick={()=>setLive(!isLive)}>{isLive?<ChevronLeft size={15}/>:<><i className="dot-success"/>Live</>}</Button></section><main className="app-main">{children}</main></div>;
}
